### ISSUE TITLE
Pictures for vec_sum2s, vec_sum4s, and vec_sums

### ISSUE THREAD

**Issue by wschmidt-ibm** [OpenPOWERFoundation/Programming-Guides#26]
PC requests pictures for these.

**Comment by ThinkOpenly** [comment]
![Screenshot from 2020-05-04 16-06-51](https://user-images.githubusercontent.com/12301795/81013963-a7e3a380-8e21-11ea-97d3-b177a025a28f.png)

**Comment by wschmidt-ibm** [comment]
The second example for vec_sum4s gets saturation wrong, since this is signed arithmetic.  The third column for **r** should say it is saturated, and the fourth column result should be 00000000.

The web version has the bullets located oddly with respect to the tables.

For vec_sums, **b** and **r** are in italics, rather than boldface.

Otherwise ok, please resubmit.

**Comment by wschmidt-ibm** [comment]
I suppose the weird bullets are an artifact of github, not the examples themselves...

**Comment by ThinkOpenly** [comment]
Those two columns in the `vec_sum4s` are indeed wrong.  The fourth column should indeed be `00000000`, but the 3rd column should actually be `7FFEFFFF` because `8421` is negative.  However, that's not what I intended, and curse me for not acutally writing and running a test.
I'll fix it up.  I don't acutally like the 3rd column as a useful example.
I'll resubmit in a bit.

**Comment by ThinkOpenly** [comment]
Oh, the bullets are not part of the images. I put the images in a list in the GitHub comment. I have not done this before, but this commit hit multiple sections.  I thought, mistakenly, that it would be clearer. :-/

**Comment by ThinkOpenly** [comment]
force pushed. ready for review again. sorry for the earlier noise. Here are updated images (differently formatted display this time):
* PDF
  * `vec_sum2s`
    > ![Screenshot from 2020-05-04 18-44-39](https://user-images.githubusercontent.com/12301795/81024001-ab822500-8e37-11ea-9039-6517c299c32f.png)
  * `vec_sum4s`
    > ![Screenshot from 2020-05-04 18-45-04](https://user-images.githubusercontent.com/12301795/81024007-afae4280-8e37-11ea-9148-3c4c761f1a7f.png)
  * `vec_sums`
    > ![Screenshot from 2020-05-04 18-45-21](https://user-images.githubusercontent.com/12301795/81024015-b341c980-8e37-11ea-83c3-6dab61e087eb.png)
* web:
  * `vec_sum2s` 
    > ![Screenshot from 2020-05-04 18-45-54](https://user-images.githubusercontent.com/12301795/81024021-b8067d80-8e37-11ea-94d4-00d997890c89.png)
  * `vec_sum4s`
    > ![Screenshot from 2020-05-04 18-46-28](https://user-images.githubusercontent.com/12301795/81024030-bfc62200-8e37-11ea-90f3-ef10bd4b99df.png)
  * `vec_sums`
    > ![Screenshot from 2020-05-04 18-46-45](https://user-images.githubusercontent.com/12301795/81024036-c5bc0300-8e37-11ea-900a-8a793d579c5e.png)

**Comment by wschmidt-ibm** [comment]
Looks good, with one nit.  vec_sum2s is missing the horizontal line at the bottom of the frame, in both PDF and web versions.  Can you please fix?

**Comment by ThinkOpenly** [comment]
Weird. I think my pictures were _both_ coincidentally poorly captured, omitting the bottom border. Unless you built the changes and see the same thing, I think it was just a poor image capture. I've recaptured the images below:
![Screenshot from 2020-05-04 21-35-41](https://user-images.githubusercontent.com/12301795/81030709-5baf5800-8e4f-11ea-8108-f5ff476e9a49.png)
![Screenshot from 2020-05-04 21-36-08](https://user-images.githubusercontent.com/12301795/81030728-75509f80-8e4f-11ea-81a8-da6babbb09d0.png)
