### ISSUE TITLE
README.md is full of lies

### ISSUE THREAD

**Issue by wschmidt-ibm** [OpenPOWERFoundation/Programming-Guides#68]
From Jinsong Ji:

"The project which controls the look and feel of the document is the Docs-Maven-Plugin project, an OpenPOWER Foundation private project on GitHub. To obtain access to the Maven Plugin project, contact Jeff Scheel (scheel@us.ibm.com) or Jeff Brown (jeffdb@us.ibm.com)."

Looks like both Jeff are not with IBM anymore....
The Docs-Maven-Plugin also not does not exist.

**Comment by jjscheel** [comment]
Then, you should change them...

**Comment by wschmidt-ibm** [comment]
Yes, precisely... this is a placeholder for that ;-)  

While you're here, you can tell us where you hid the plugin! :-D

**Comment by toshywoshy** [comment]
If it is just the README.md, I updated it to the tsc chair email
For now that is me, but the generic mail gets redirected to the current TSC Chair

**Comment by wschmidt-ibm** [comment]
Thanks, that's great!  We still need to figure out where the Docs-Maven-Plugin project went; last I heard, nobody could find it.

**Comment by wschmidt-ibm** [comment]
OK, this is now solved.  The link is actually fine, but access to the repository is restricted.  I think we should just point that out in the README.md and point people to the TSC chair for access.  Thanks to Klaus for responding and clearing this up.

**Comment by wschmidt-ibm** [comment]
I see that this has all been addressed; closing.
