### ISSUE TITLE
[PVIPR] vec_cpsgn reverses the meaning of the parameters

### ISSUE THREAD

**Issue by ThinkOpenly** [OpenPOWERFoundation/Programming-Guides#74]
`vec_cpsgn` says:
> Result value: The value of each element of **r** is set to the corresponding element of **b** with its sign replaced by the sign from the corresponding element of **a**.

However, the implementation returns the elements of **a** with the signs from **b**.

**Comment by wschmidt-ibm** [comment]
To be clear, both instances of "r,b,a" should be changed to "r,a,b".

Thanks for the report!
